name: Playwright Tests
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: feedbackapp_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Setup environment variables
      run: |
        echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/feedbackapp_test" >> $GITHUB_ENV
        echo "SHADOW_DATABASE_URL=postgresql://postgres:postgres@localhost:5432/feedbackapp_shadow_test" >> $GITHUB_ENV
        echo "NEXT_PUBLIC_APP_URL=http://localhost:3000" >> $GITHUB_ENV
        echo "GOOGLE_CLIENT_ID=test_client_id" >> $GITHUB_ENV
        echo "GOOGLE_CLIENT_SECRET=test_client_secret" >> $GITHUB_ENV
        
    - name: Generate Prisma client
      run: npx prisma generate
      
    - name: Setup test database
      run: |
        npx prisma migrate deploy
        
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      
    - name: Run linting
      run: npm run lint || true # Continue even if linting fails
      
    - name: Build application
      run: npm run build
      
    - name: Run Playwright tests
      run: npm run test:e2e
      env:
        CI: true
        
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
        
    - uses: actions/upload-artifact@v4
      if: failure()  
      with:
        name: test-results
        path: test-results/
        retention-days: 30